#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'

Bundler.require(:default)

ENV["RACK_ENV"] ||= "production"

$:.unshift File.expand_path(File.join(File.dirname(__FILE__), '..', 'lib'))


require 'command_interpretor'
require 'simulation/robot'

if __FILE__ == $0
  grid  = Simulation::Grid.new(5,5)
  robot = Simulation::Robot.new(grid)
  cmd_interpretor = CommandInterpretor.new(robot)
  File.open("./scripts/command.txt").each_line do |cmd_str|
    begin
    puts cmd_str
    cmd = cmd_interpretor.interpret(cmd_str)
    cmd.execute
  rescue => e
    Simulation.logger.error("Invalid command: #{cmd_str}. Ready for next command.")
  end
  end
end
